### ISSUE TITLE
Info about Features Vector

### ISSUE THREAD

**Issue by mastiffs92** [bytefish/libfacerec#23]
Hello,
I'm using your fantastic library, I need to extract the features from lbp from the pictures, I used the files lbp.cpp lbp.hpp helper.cpp helper.hpp building this 'main.cpp':
![screen_features_lbp](https://cloud.githubusercontent.com/assets/15649307/13502150/108e7f54-e16a-11e5-87b2-9585e20f8455.png)
I memorize the feature vector in .yml file.
okay as I did? I can use many of these feature vector for how many images to train the svm?
I took the liberty of making this account because I have noticed that in the function 'spatial_histogram' present in 'lbp.cpp' file there is a comment saying:
`// Return result as reshaped feature vector`
`return result.reshape  (1,1);`
Thanks in advance for answers

**Comment by kuroganashi** [comment]
:smiley_cat:

**Comment by bytefish** [comment]
I haven't worked with OpenCV in a long time, so at the moment I am not able to check if your program works correctly. However if you want to assert, that code works correctly I suggest refactoring it into testable parts and write Unit Tests for it. 

The Unit Tests I have written for the FaceRecognizers FileStorage methods can be found at: [https://github.com/bytefish/libfacerec/blob/master/test/test_helper.cpp](test_helper.cpp), they might give you an idea.

I have no experiences in using Local Binary Patterns with Support Vector Machines. The training set size will depend on the problem you are trying to solve. I would try to find some papers, that are related to your problem and look at the data sets they have used.

**Comment by kuroganashi** [comment]
This is an amazing project indeed, I shared with my Group and all :D 

But there is something that does the same function nowdays, it is alot more complex tho but it is fun to work with.

**Comment by bytefish** [comment]
I am closing this Issue as wontfix.

**Comment by mastiffs92** [comment]
@bytefish Thanks for the answer.
@kuroganashi have you experiences with opencv? do you think this program can function?

**Comment by kuroganashi** [comment]
@mastiffs92 Yes, it is a very tangible thing to do, we would have to work our way around it tho as this can be improved.

@bytefish I believe you should keep this as reference material. (even tho what you said is true, this can be helpful in the future as Reference.)
